import type { Metadata } from "next";
import "./globals.css";
import {
	ColorSchemeScript,
	MantineProvider,
	createTheme,
	AppShell,
	AppShellMain,
} from "@mantine/core";
import HeaderMenu from "@/components/HeaderMenu";

export const metadata: Metadata = {
	title: "HandSpeak",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider theme={createTheme({})}>
					<AppShell header={{ height: 75 }}>
						<HeaderMenu />
						<AppShellMain>{children}</AppShellMain>
					</AppShell>
				</MantineProvider>
			</body>
		</html>
	);
}
