"use client";
import type { Metadata } from "next";
import "./globals.css";
import {
	ColorSchemeScript,
	MantineProvider,
	createTheme,
	AppShell,
	AppShellMain,
} from "@mantine/core";
import HeaderMenu from "@/components/HeaderMenu";
import { useDisclosure } from "@mantine/hooks";

/* export const metadata: Metadata = {
	title: "HandSpeak",
	description: "Generated by create next app",
}; */

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [opened, { toggle }] = useDisclosure();
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
			</head>
			<body>
				<MantineProvider theme={createTheme({})}>
					<AppShell
						header={{ height: 75 }}
						aside={{
							width: 300,
							breakpoint: "sm",
							collapsed: { desktop: true, mobile: !opened },
						}}
					>
						<HeaderMenu opened={opened} toggle={toggle} />
						<AppShellMain>{children}</AppShellMain>
					</AppShell>
				</MantineProvider>
			</body>
		</html>
	);
}
